version: '{build}'

build_script:
    - ps: |
        if ( !(Test-Path "$env:APPVEYOR_BUILD_FOLDER\work\appveyorHelp.psm1"))
        {
            mkdir $env:APPVEYOR_BUILD_FOLDER\work\
            Start-FileDownload https://raw.githubusercontent.com/TheOneRing/appVeyorHelp/master/appveyorHelp.psm1 -FileName $env:APPVEYOR_BUILD_FOLDER\work\appveyorHelp.psm1 
        }
        $ErrorActionPreference="Stop"

        Import-Module $env:APPVEYOR_BUILD_FOLDER\work\appveyorHelp.psm1

        Init @("ninja", "png2ico") ([ordered]@{ "git://anongit.kde.org/extra-cmake-modules.git" = @{"branch" = "master"};
                                                "https://github.com/Snorenotify/SnoreGrowl.git" = @{"branch" = "v0.4.0"}})

        mkdir -Force $env:APPVEYOR_BUILD_FOLDER\work\build\snorenotify
        cd $env:APPVEYOR_BUILD_FOLDER\work\build\snorenotify
        LogExec cmake -G"Ninja" $env:APPVEYOR_BUILD_FOLDER -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$CMAKE_INSTALL_ROOT"
        CmakeImageInstall




test: off

cache:
    - work\install -> appveyor.yml
    - C:\ProgramData\chocolatey\bin -> appveyor.yml
    - C:\ProgramData\chocolatey\lib -> appveyor.yml
    - work\appveyorHelp.psm1 -> appveyor.yml

environment:
    QT_VER: 5.5
    
    matrix:
    #mingw
    - COMPILER: mingw492_32
    #msvc
    - COMPILER: msvc2013_64
    